spring.application.name=hotel-haven
spring.datasource.url=jdbc:h2:mem:hotelhaven;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.thymeleaf.cache=false
server.port=8080
